### ISSUE TITLE
Icons and possible segfault

### ISSUE THREAD

**Issue by timholy** [JuliaGraphics/Immerse.jl#13]
OSX users seem to get some pretty non-intuitive icons (see #11).

@pagnani also reported a segfault when clicking the "Save as" icon twice; @pagnani, can you provide more detail? Did the save dialog open after the first click?

**Comment by pagnani** [comment]
Yes I click the first time and nothing happens, then a second one and after a couple of seconds it hangs. On my shell the last two output are 
```
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
Segmentation fault: 11
```

**Comment by timholy** [comment]
Can you test this:
```jl
using Gtk
ret = Gtk.save_dialog("Save file as")
```
It should show you a dialog something like this:
![image](https://cloud.githubusercontent.com/assets/1525481/10071161/1e40a986-627d-11e5-8f4e-8686ed0d4e65.png)

**Comment by pagnani** [comment]
Yes it works ... it also allows me to browse the dir entering and all that

<img width="749" alt="screen shot 2015-09-24 at 1 01 02 pm" src="https://cloud.githubusercontent.com/assets/1280414/10071762/9c79fff2-62bc-11e5-8838-dcf6efd78732.png">

**Comment by timholy** [comment]
OK, let's move this over to Gtk.

**Comment by timholy** [comment]
If you try `Pkg.checkout("Immerse")`, things should be working for you. If you'd test and let me know, I'd be grateful.

**Comment by pagnani** [comment]
Yes now it works without any crash. It also allows me to export as pdf the
plot!

Very Good!



On Thu, Sep 24, 2015 at 3:02 PM, Tim Holy <notifications@github.com> wrote:

> If you try Pkg.checkout("Immerse"), things should be working for you. If
> you'd test and let me know, I'd be grateful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaGraphics/Immerse.jl/issues/13#issuecomment-142920632>
> .
>



-- 
-------------------------------------------------------------
Politecnico Torino
Corso Duca degli Abruzzi 24,
I-10129 Torino - Italy

Human Genetics Foundation (HuGeF)
Via Nizza 52
I-10126 Torino - Italy

web: http://www.polito.it/cmp/home/pagnani
Tel: +39-0110916488
Fax +39-0116709546
-------------------------------------------------------------

**Comment by timholy** [comment]
Thanks. I just tagged a new version. If you prefer to track just the tagged releases going forward, you can say `Pkg.update(); Pkg.free("Immerse")`. (Or just keep things the way you have them now, and you'll always have the very latest version.)
