### ISSUE TITLE
Lots of deprecations for Julia 0.4.0

### ISSUE THREAD

**Issue by lewisl** [JuliaGraphics/Immerse.jl#18]
Mostly Base.Uint8 should be new UInt8.  Others.  Just Pkg.add() then using...  and you'll see them. On Mac OS X El Capitan.

**Comment by lewisl** [comment]
Actually, it's worse than that.  Precompile fails.

**Comment by timholy** [comment]
Better to paste your output---there's nothing I can do with this as a bug report.

The only Uint8 deprecations that I experience myself are from the `gen` folder in Gtk.jl, and I'm unclear on how to regenerate those files (CC @vtjnash). However, it's possible I'm running master on some package that needs to be tagged, in which case pasting your output would help me figure out which one that is.

**Comment by timholy** [comment]
(Also, precompile works fine for me.)

**Comment by lewisl** [comment]
You are right the problem appears to be with gtk.  This output isn't as long as the first time.  I tried to Pkg.rm everything but a variety of detritus remains in various caches--to make it "easier" next time.  What to do about gtk?  This is the problem with deep OSS dependency stacks...

=========================================
julia> Pkg.add("Plots")
INFO: Installing Plots v0.4.1
INFO: Package database updated

julia> Pkg.add("Immerse")
INFO: Installing Gtk v0.9.2
INFO: Installing GtkUtilities v0.0.6
INFO: Installing Immerse v0.0.8
INFO: Building Homebrew
remote: Counting objects: 119, done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 119 (delta 92), reused 99 (delta 72), pack-reused 0
Receiving objects: 100% (119/119), 15.18 KiB | 0 bytes/s, done.
Resolving deltas: 100% (92/92), completed with 23 local objects.
From https://github.com/Homebrew/homebrew
   e37f843..9133034  master     -> origin/master
HEAD is now at 9133034 leafnode: fix runtime issues
HEAD is now at ce3d0c3 Merge pull request #78 from staticfloat/staging
INFO: Building Cairo
INFO: Building Gtk
INFO: Package database updated

julia> Using Plots
ERROR: syntax: extra token "Plots" after end of expression

julia> using Plots
INFO: Recompiling stale cache file /Users/lewislevinmbr/.julia/lib/v0.4/Plots.ji for module Plots.

julia> using Immerse
INFO: Recompiling stale cache file /Users/lewislevinmbr/.julia/lib/v0.4/Cairo.ji for module Cairo.
INFO: Recompiling stale cache file /Users/lewislevinmbr/.julia/lib/v0.4/Compose.ji for module Compose.
INFO: Recompiling stale cache file /Users/lewislevinmbr/.julia/lib/v0.4/Gadfly.ji for module Gadfly.
WARNING: eval from module Compose to Gadfly:    
Expr(:import, :Patchwork)::Any
  ** incremental compilation may be broken for this module **


INFO: Recompiling stale cache file /Users/lewislevinmbr/.julia/lib/v0.4/Immerse.ji for module Immerse.
INFO: Recompiling stale cache file /Users/lewislevinmbr/.julia/lib/v0.4/GtkUtilities.ji for module GtkUtilities.
INFO: Recompiling stale cache file /Users/lewislevinmbr/.julia/lib/v0.4/Gtk.ji for module Gtk.
2015-10-27 10:01:39.749 julia[18337:52729] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near /Users/lewislevinmbr/.julia/v0.4/GtkUtilities/src/link.jl:110
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near /Users/lewislevinmbr/.julia/v0.4/GtkUtilities/src/link.jl:110
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near /Users/lewislevinmbr/.julia/v0.4/GtkUtilities/src/link.jl:110
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near /Users/lewislevinmbr/.julia/v0.4/GtkUtilities/src/link.jl:110
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near /Users/lewislevinmbr/.julia/v0.4/GtkUtilities/src/link.jl:110
2015-10-27 10:01:42.096 julia[18336:52710] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
WARNING: Method definition draw(Compose.Backend, Compose.Context) in module Compose at /Users/lewislevinmbr/.julia/v0.4/Compose/src/container.jl:404 overwritten in module Immerse at /Users/lewislevinmbr/.julia/v0.4/Immerse/src/compose.jl:33.
WARNING: Method definition display(Base.REPL.REPLDisplay, Base.Multimedia.MIME{:text/html}, Gadfly.Plot) in module Gadfly at /Users/lewislevinmbr/.julia/v0.4/Gadfly/src/Gadfly.jl:969 overwritten in module Immerse at /Users/lewislevinmbr/.julia/v0.4/Immerse/src/display_gadfly.jl:144.
2015-10-27 10:01:49.439 julia[14712:40502] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
WARNING: Method definition display(Base.REPL.REPLDisplay{R<:Base.REPL.AbstractREPL}, Base.Multimedia.MIME{:text/html}, Gadfly.Plot) in module Gadfly at /Users/lewislevinmbr/.julia/v0.4/Gadfly/src/Gadfly.jl:969 overwritten in module Immerse at /Users/lewislevinmbr/.julia/v0.4/Immerse/src/display_gadfly.jl:144.
WARNING: Method definition draw(Compose.Backend, Compose.Context) in module Compose at /Users/lewislevinmbr/.julia/v0.4/Compose/src/container.jl:404 overwritten in module Immerse at /Users/lewislevinmbr/.julia/v0.4/Immerse/src/compose.jl:33.

julia> gadfly()
Plots.GadflyPackage()

julia> scatter([1,2,3,4],[1,2,3,4])
[Plots.jl] Initializing backend: gadfly

(<unknown>:14712): GLib-GObject-WARNING **: The property GtkToolButton:stock-id is deprecated and shouldn't be used anymore. It will be removed in a future version.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
=========> the plot window appears properly...


====== starting over in new Julia session:
julia> using Plots

julia> immerse()
Plots.ImmersePackage()

julia> plot(1:4)
[Plots.jl] Initializing backend: immerse
2015-10-27 10:10:43.438 julia[18531:61008] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
WARNING: Method definition display(Base.REPL.REPLDisplay{R<:Base.REPL.AbstractREPL}, Base.Multimedia.MIME{:text/html}, Gadfly.Plot) in module Gadfly at /Users/lewislevinmbr/.julia/v0.4/Gadfly/src/Gadfly.jl:969 overwritten in module Immerse at /Users/lewislevinmbr/.julia/v0.4/Immerse/src/display_gadfly.jl:144.
WARNING: Method definition draw(Compose.Backend, Compose.Context) in module Compose at /Users/lewislevinmbr/.julia/v0.4/Compose/src/container.jl:404 overwritten in module Immerse at /Users/lewislevinmbr/.julia/v0.4/Immerse/src/compose.jl:33.

(<unknown>:18531): GLib-GObject-WARNING **: The property GtkToolButton:stock-id is deprecated and shouldn't be used anymore. It will be removed in a future version.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
=========> the plot window appears properly...

**Comment by tbreloff** [comment]
Looks like it started up ok, with a few dep warnings in Gtk.  There are certainly some annoying warnings with Gtk on OSX... I've seen similar (at least they aren't errors ;)  The method definition errors are unavoidable unless that logic is changed within core Julia, since Immerse overwrites/replaces the Gadfly methods.

Final note... you don't need the `using Immerse` after `using Plots`.

**Comment by timholy** [comment]
This has been fixed with the latest release.
