### ISSUE TITLE
Error when zoom is used

### ISSUE THREAD

**Issue by jverzani** [JuliaGraphics/Immerse.jl#52]
Hi @timholy In trying to get GtkInteract to work with Immerse I found a condition that generates a crash. Here are the steps:

```
using Immerse
plot(x=rand(6), y=rand(6))
```

Click on magnifying glass and select a region to zoom, then

```
plot(x=rand(6), y=rand(6))
```

Then try selecting a region to zoom. These steps result in:

```
ERROR: KeyError: xview not found
 in getindex at /Users/verzani/.julia/v0.4/GtkUtilities/src/guidata.jl:28
 in zoom_bb at /Users/verzani/.julia/v0.4/GtkUtilities/src/panzoom.jl:464
 in anonymous at /Users/verzani/.julia/v0.4/GtkUtilities/src/panzoom.jl:412
 in rubberband_stop at /Users/verzani/.julia/v0.4/GtkUtilities/src/rubberband.jl:109
 in anonymous at /Users/verzani/.julia/v0.4/GtkUtilities/src/rubberband.jl:75
 in mouseup_cb at /Users/verzani/.julia/v0.4/Gtk/src/events.jl:177
 in anonymous at /Users/verzani/.julia/v0.4/Gtk/src/events.jl:2
 in g_sigatom at /Users/verzani/.julia/v0.4/Gtk/src/GLib/signals.jl:168
 in gtk_main at /Users/verzani/.julia/v0.4/Gtk/src/events.jl:1
```

This all on my macbook.

I don't know if just checking existence of the key `xview` is sufficient, or if the `guidata` is using a new canvas object for the look up.

**Comment by timholy** [comment]
Good catch, thanks.

**Comment by jverzani** [comment]
Thanks! It came up when I was trying to get Immerse support into
GtkInteract. I think that is basically working now if you wanted to try it
out.

On Sun, Nov 22, 2015 at 9:50 AM, Tim Holy <notifications@github.com> wrote:

> Good catch, thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaGraphics/Immerse.jl/issues/52#issuecomment-158764759>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by timholy** [comment]
That is super-sweet! Thanks for tackling it.
