### ISSUE TITLE
Making Figure usable inside another Gtk application?

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaGraphics/Immerse.jl#58]
I've been playing a bit with using Immerse in a Gtk application, the main change I had to do is to make Figure a subtype of GtkWidget, so it can be pushed inside a GtkContainer. Then I can overwrite `Immerse.figure` in my code to push the figure inside a container instead of putting it in a new window:

http://i.imgur.com/XA6waa8.png

Would that be a viable design for Immerse, or is there a reason why Figure isn't a Widget ?

The only issue I still have is that my plots do not display (I really don't understand how this display business works), so I have to call display(plot(...

https://github.com/JuliaGraphics/Immerse.jl/compare/master...jonathanBieler:widget_fig

(I also reduced the icon size)

**Comment by timholy** [comment]
That's interesting. Probably worth having. It's not immediately obvious to me that `GtkBox` is the best container, but it doesn't seem crazy either, and I haven't taken the time to think of a better alternative.

As far as display goes, you may find this informative:
```jl
julia> x = linspace(0,5pi, 1001)
linspace(0.0,15.707963267948966,1001)

julia> p = plot(x=x, y=sin(x), Geom.line);  # no window opens after this line executes

julia> p  # now the window opens and the graph is drawn
```
It's the REPL itself calling `display`. You'd have to make sure that whatever object returned by `plot` (or whatever command you're using) has the appropriate `display` method defined.

**Comment by jonathanBieler** [comment]
Ok I get it now, thanks.

I think `GtkBox` is not too bad; a figure is some rectangular area with a drawing and maybe a few things on top or bottom. If you go up one level to `GtkContainer` you have things  like notebooks, or pans which are not really what you except for a figure.
