### ISSUE TITLE
error on precompilation on linux

### ISSUE THREAD

**Issue by adhalanay** [JuliaGraphics/Immerse.jl#61]
Precompilation fails with 

`INFO: Precompiling module Immerse...
ERROR: LoadError: LoadError: UndefVarError: absolute_native_units not defined
while loading /home/andrei/.julia/v0.4/Immerse/src/compose.jl, in expression starting on line 13
while loading /home/andrei/.julia/v0.4/Immerse/src/Immerse.jl, in expression starting on line 31
ERROR: Failed to precompile Immerse to /home/andrei/.julia/lib/v0.4/Immerse.ji
 in compilecache at ./loading.jl:384`

Julia versioninfo() gives:
Commit a2f713d (2016-01-12 21:37 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: AMD FX(tm)-8350 Eight-Core Processor
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Piledriver)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.8

**Comment by timholy** [comment]
You probably have a branch or pinned version on Compose. Check `Pkg.status()` and consider `Pkg.free("Compose")`.

**Comment by adhalanay** [comment]
Compose was installed as a dependency of Immerse at it seemed to be the last version. Anyway after removing all packages and reinstalling Immerse the compilation worked. So I guess you can close the issue.

**Comment by timholy** [comment]
Hmm, confusing. If you have any similar troubles and get a sense of what happened, feel free to reopen.
