### ISSUE TITLE
LoadError: UndefVarError: mac not defined

### ISSUE THREAD

**Issue by manojcent** [JuliaGraphics/Immerse.jl#72]
getting  this error on window machine while running CPLEX

    for t=1:PlanningPeriod
          for p=1:NumberofProducttypes
            for i=1:depot-nDepots
              @addConstraints(m,sum{z_ijtpv[j,i,t,p,v],v=1:NumerOfVehicle,j=1:i-1}+sum{z_ijtpv[j,i,t,p,v],v=1:NumerOfVehicle,j=i+1:depot-nDepots}
              -sum{z_ijtpv[i,j,t,p,v],v=1:NumerOfVehicle,j=1:i-1}-sum{z_ijtpv[i,j,t,p,v],v=1:NumerOfVehicle,jj=i+1:depot-nDepots}==r_itp[j,t,p]);
            end
          end
        end

**Comment by timholy** [comment]
Not sure what this has to do with Immerse? Did you mean to report this to JuMP?

**Comment by manojcent** [comment]
Thanks Tim
Reported to JuMP and resolved now.

Thanks and Regards,
Manoj Kumar
