### ISSUE TITLE
Precompile failed on JuliaPro 0.5.2.2  Windows x64

### ISSUE THREAD

**Issue by pemryan** [JuliaGraphics/Immerse.jl#73]
julia> Pkg.add("Immerse")
INFO: Cloning cache of Docile from https://github.com/MichaelHatherly/Docile.jl.git
INFO: Cloning cache of GtkUtilities from https://github.com/timholy/GtkUtilities.jl.git
INFO: Cloning cache of Immerse from https://github.com/JuliaGraphics/Immerse.jl.git
INFO: Installing Docile v0.5.23
INFO: Installing GtkUtilities v0.1.0
INFO: Installing Immerse v0.0.13
INFO: Building WinRPM
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repos
itories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repos
itories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Building Cairo
WARNING: BinDeps.shlib_ext is deprecated.
  likely near C:\JuliaPro-0.5.2.2\pkgs-0.5.2.2\v0.5\Cairo\deps\build.jl:112
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repos
itories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repos
itories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Building Gtk
INFO: Nothing to do
INFO: Building Rmath
INFO: Package database updated

julia> using Immerse, Distributions
INFO: Precompiling module Immerse.
WARNING: @Gtk.GtkLabel is deprecated, use Gtk.GtkLabel instead.
 in depwarn(::String, ::Symbol) at .\deprecated.jl:64
 in @GtkLabel(::Expr, ::Vararg{Expr,N}) at C:\JuliaPro-0.5.2.2\pkgs-0.5.2.2\v0.5
\Gtk\src\GLib\gtype.jl:223
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:242
 in _start() at .\client.jl:321
while loading C:\JuliaPro-0.5.2.2\pkgs-0.5.2.2\v0.5\GtkUtilities\src\link.jl, in
 expression starting on line 209
WARNING: @Gtk.GtkEntry is deprecated, use Gtk.GtkEntry instead.
 in depwarn(::String, ::Symbol) at .\deprecated.jl:64
 in @GtkEntry(::Expr, ::Vararg{Expr,N}) at C:\JuliaPro-0.5.2.2\pkgs-0.5.2.2\v0.5
\Gtk\src\GLib\gtype.jl:223
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:242
 in _start() at .\client.jl:321
while loading C:\JuliaPro-0.5.2.2\pkgs-0.5.2.2\v0.5\GtkUtilities\src\link.jl, in
 expression starting on line 238
WARNING: @Gtk.GtkAdjustment is deprecated, use Gtk.GtkAdjustment instead.
 in depwarn(::String, ::Symbol) at .\deprecated.jl:64
 in @GtkAdjustment(::Expr, ::Vararg{Expr,N}) at C:\JuliaPro-0.5.2.2\pkgs-0.5.2.2
\v0.5\Gtk\src\GLib\gtype.jl:223
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:242
 in _start() at .\client.jl:321
while loading C:\JuliaPro-0.5.2.2\pkgs-0.5.2.2\v0.5\GtkUtilities\src\link.jl, in
 expression starting on line 257
WARNING: @Gtk.GtkAdjustment is deprecated, use Gtk.GtkAdjustment instead.
 in depwarn(::String, ::Symbol) at .\deprecated.jl:64
 in @GtkAdjustment(::Expr, ::Vararg{Expr,N}) at C:\JuliaPro-0.5.2.2\pkgs-0.5.2.2
\v0.5\Gtk\src\GLib\gtype.jl:223
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:242
 in _start() at .\client.jl:321
while loading C:\JuliaPro-0.5.2.2\pkgs-0.5.2.2\v0.5\GtkUtilities\src\link.jl, in
 expression starting on line 263
WARNING: @Gtk.GtkScale is deprecated, use Gtk.GtkScale instead.
 in depwarn(::String, ::Symbol) at .\deprecated.jl:64
 in @GtkScale(::Expr, ::Vararg{Expr,N}) at C:\JuliaPro-0.5.2.2\pkgs-0.5.2.2\v0.5
\Gtk\src\GLib\gtype.jl:223
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:242
 in _start() at .\client.jl:321
while loading C:\JuliaPro-0.5.2.2\pkgs-0.5.2.2\v0.5\GtkUtilities\src\link.jl, in
 expression starting on line 268
ERROR: LoadError: LoadError: UndefVarError: absolute_native_units not defined
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:242
 in _start() at .\client.jl:321
while loading C:\JuliaPro-0.5.2.2\pkgs-0.5.2.2\v0.5\Immerse\src\compose.jl, in e
xpression starting on line 13
while loading C:\JuliaPro-0.5.2.2\pkgs-0.5.2.2\v0.5\Immerse\src\Immerse.jl, in e
xpression starting on line 31
ERROR: Failed to precompile Immerse to C:\Users\dell\.julia\lib\v0.5\Immerse.ji.

 in compilecache(::String) at .\loading.jl:593
 in require(::Symbol) at .\loading.jl:422

**Comment by cjruiz** [comment]
Same error in 0.6 version, did you fixed it?

**Comment by timholy** [comment]
I can't replicate this on 0.6. Are you using `master` on Compose? We might want to add an upper bound to Immerse if newer versions of Compat break this. I don't use Gadfly much anymore so this may require community input for a proper fix.

**Comment by pemryan** [comment]
This error doesn't happen anymore on 0.6.1 windows 7 x64.  It only complains about several  typealias (deprecated syntax) when pre-compiling.
