### ISSUE TITLE
move this repository to JuliaPlot?

### ISSUE THREAD

**Issue by lobingera** [JuliaGraphics/Immerse.jl#8]

**Comment by timholy** [comment]
I'm not sure where it belongs. It combines a plotting package (Gadfly) with a graphics package (Gtk). To be honest, I'm not sure we need both JuliaPlot and JuliaGraphics, and JuliaGraphics has more code in it :smile:.

**Comment by tbreloff** [comment]
I must say I was having the exact same thought yesterday, and almost created an issue. I agree that JuliaGraphics is a better home for the documents/discussions currently at JuliaPlot.
