### ISSUE TITLE
Why Gadfly has no Immerse's features, i.e. lasso, hit, set? 

### ISSUE THREAD

**Issue by HackYardo** [JuliaGraphics/Immerse.jl#92]
What do you mean by 'Currently, Immerse supports Gadfly'? Gadfly's doc website has no words about lasso, hit, set, and no Immerse in Gadfly's github branches.

**Comment by jonathanBieler** [comment]
Immerse adds these features to Gadfly and Gadfly only (presumably it could support other plotting backends, e.g. Makie).

**Comment by HackYardo** [comment]
Thanks for your reply!
I want to create a **game GUI** in julia, however, 
- GTK & QML look like work not well on win10;
- Makie is slow when startup even by sysimage;
- Plots has no mouse&keyboard events features;
- pyplot.jl is python not julia;
- etc

Now I turn to **Plotly Dash.jl**, hope everything is just fine!
